# -*- coding: utf-8 -*-
"""kasir

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cJ9ehqpuYQXAhlL4EYOgrEQqDQI9JToU
"""

import numpy as np
import pandas as pd
from tabulate import tabulate
class Transaction:

    # Initiate empty dict and assign to DataFrame
    empty_dict = {"Item": [], "JumlahBarang": [], "Harga": []}
    data = pd.DataFrame(empty_dict)

    """Membuat Fungsi untuk menambahkan nama_item, jumlah_item, harga_item
            ke dalam attribute class data"""
          
    def add_item(
        self, nama_item: str, jumlah_item: int, harga_item: float or int
    ):
        # Check type of data parameter nama_item
        if type(nama_item) != str:
            raise TypeError()

        # Check type of data parameter jumlah_item
        elif type(jumlah_item) != int:
            raise TypeError()
        # Check type of data parameter harga_item
        elif type(harga_item) != float and type(harga_item) != int:
            raise TypeError()
        else:
            # Assign parameter into attribute class data
            self.data.loc[len(self.data)] = [
                nama_item,
                jumlah_item,
                harga_item,
            ]
            print("Item yang Anda masukan:")
            print(f"Nama Item     : {nama_item}")
            print(f"Jumlah Barang : {jumlah_item}")
            print(f"Harga per-Item: Rp. {harga_item}")

    """Membuat Fungsi untuk mengupdate nama_item jika nama_item terdapat
            dalam attribute class data"""
            
    def update_item_name(self, nama_item: str, update_nama_item: str):
        # Create list of all item in attribute class data
        list_nama_item = self.data["Item"].tolist()
        try:
            # Check parameter nama_item in list_nama_item
            if nama_item not in list_nama_item:
                raise ValueError
            else:
                # Check type of data parameter nama_item
                if type(nama_item) != str:
                    raise TypeError()
                # Check type of data parameter update_nama_item
                elif type(update_nama_item) != str:
                    raise TypeError()
                else:
                    # Filter by name_item
                    # assign update_nama_item in attribute class data
                    self.data.loc[
                        self.data.Item == nama_item, "Item"
                    ] = update_nama_item
                    print(
                        f"Anda merubah {nama_item} menjadi {update_nama_item}"
                    )

        except ValueError:
            print(f"Item {nama_item} tidak ditemukan dalam sesi transaksi ini")

    """Fungsi untuk mengupdate jumlah_item dalam jika nama_item
            terdapat dalam attribute class data"""

    def update_item_qty(self, nama_item: str, update_jml_item: int):

        # Create list of all item in attribute class data
        list_nama_item = self.data["Item"].tolist()
        try:
            # Check parameter nama_item in list_nama_item
            if nama_item not in list_nama_item:
                raise ValueError
            else:
                # Check type of data parameter nama_item
                if type(nama_item) != str:
                    raise TypeError(
                        "Parameter 'nama_item' harus memiliki tipe data 'str'"
                    )
                # Check type of data parameter update_jml_item
                elif type(update_jml_item) != int:
                    raise TypeError(
                        "Parameter 'update_jml_item' memiliki tipe data 'int'"
                    )
                else:
                    # Filter by nama_item
                    # assign update_jml_item in attribute class data
                    self.data.loc[
                        self.data.Item == nama_item, "JumlahBarang"
                    ] = update_jml_item
                    print(
                        f"Anda merubah Jumlah {nama_item} menjadi {update_jml_item}"
                    )

        except ValueError:
            print(f"Item {nama_item} tidak ditemukan dalam sesi transaksi ini")

    """Fungsi untuk mengupdate harga dalam jika nama_item terdapat
            dalam attribute class data"""

    def update_item_price(self, nama_item: str, update_harga: float or int):
      
        # Create list of all item in attribute class data
        list_nama_item = self.data["Item"].tolist()
        try:
            # Check parameter nama_item in list_nama_item
            if nama_item not in list_nama_item:
                raise ValueError

            else:
                # Check type of data parameter nama_item
                if type(nama_item) != str:
                    raise TypeError(
                        "Parameter 'nama_item' harus memiliki tipe data 'str'"
                    )

                # Check type of data parameter update_harga
                elif type(update_harga) != float and type(update_harga) != int:
                    raise TypeError(
                        "Parameter 'update_harga' memiliki tipe data float/int"
                    )

                else:
                    # Filter by nama_item
                    # assign update_harga in attribute class data
                    self.data.loc[
                        self.data.Item == nama_item, "Harga"
                    ] = update_harga
                    print(
                        f"Anda merubah harga {nama_item} menjadi {update_harga}"
                    )

        except ValueError:
            print(f"Item {nama_item} tidak ditemukan dalam sesi transaksi ini")
   
    """Fungsi untuk menghapus salah satu item yang terdapat dalam
            attribute class data"""

    def delete_item(self, nama_item: str):

        # Create list of all item in attribute class data
        list_nama_item = self.data["Item"].tolist()
        try:
            # Check parameter nama_item in list_nama_item
            if nama_item not in list_nama_item:
                raise ValueError

            else:
                # Check type of data parameter nama_item
                if type(nama_item) != str:
                    raise TypeError(
                        "Parameter 'nama_item' harus memiliki tipe data 'str'"
                    )
                else:
                    # Show deleted item
                    print(
                        f"Anda telah menghapus item {nama_item} dari transaksi"
                    )

                    # Filter and drop by nama_item
                    data = self.data.drop(
                        self.data.index[self.data.Item == nama_item],
                        inplace=True,
                    )

                    # Assign and show table
                    table = tabulate(data, headers="keys", tablefmt="psql")

                    return print(table)

        except ValueError:
            print(f"Item {nama_item} tidak ditemukan dalam sesi transaksi ini")

    """Fungsi untuk menghapus semua item dalam attribute class data"""
    def reset_transaction(self):

        # Show blank table
        print("Semua item berhasil di delete!")

        # Drop index in attribute class data
        self.data.drop(self.data.index, inplace=True)

        # Create  and show table
        table = tabulate(self.data, headers="keys", tablefmt="psql")

        return print(table)

    """Fungsi untuk menghitung dan menampilkan total harga untuk tiap item"""
    def check_order(self):
        # Copy attribute class data
        output_data = self.data.copy()

        # Create new column
        output_data["TotalHarga"] = (
            output_data.JumlahBarang * output_data.Harga
        )
        # Create and show table
        table = tabulate(output_data, headers="keys", tablefmt="psql")

        return print(table)
    """Fungsi untuk menghitung total transaksi beserta diskonnya"""
    def total_price(self):
        # Copy attribute class data
        output_data = self.data.copy()
        # Create new column
        output_data["TotalHarga"] = (
            output_data.JumlahBarang * output_data.Harga
        )
        # Assign variable total payment
        total = np.sum(output_data.TotalHarga)

        # If total payment les than 200.000 get normal price
        if total >= 0 and total <= 200_000:
            return print(f"Total Transaksi Anda adalah Rp.{int(total)}")

        # if total paymen more than 200.000 and less than 300.000
        # Get 5 percent discount
        elif total > 200_000 and total <= 300_000:
            total_belanja = total * 0.95
            return print(
                f"Total Transaksi Anda adalah Rp.{int(total_belanja)}"
            )

        # if total paymen more than 300.000 and less than 500.000
        # Get 8 percent discount
        elif total > 300_000 and total <= 500_000:
            total_belanja = total * 0.92
            return print(
                f"Total Transaksi Anda adalah Rp.{int(total_belanja)}"
            )

        # if total paymen more than 500.000, get 10 percent discount
        elif total > 500_000:
            total_belanja = total * 0.90
            return print(
                f"Total Transaksi Anda adalah Rp.{int(total_belanja)}"
            )

        else:
            return "Total Belanja Tidak Boleh Negatif"



